### ISSUE TITLE
bug: Resizing with mouse does not work

### ISSUE THREAD

**Issue by JelteF** [folke/edgy.nvim#107]
### Did you check docs and existing issues?

- [X] I have read all the edgy.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of edgy.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev (Ubuntu nightly)

### Operating system/version

Ubuntu 24.04

### Describe the bug

To resize the side windows I try to drag the edges with the mouse. This works for a fraction of a second but then the size snaps back to the previous size.

### Steps To Reproduce

1. Open LazyVim
2. <leader>e
3. drag edge of sidebar

### Expected Behavior

sidebar resizes and stays resized

**Comment by folke** [comment]
Check the docs. That doesn't work indeed
