### ISSUE TITLE
feature: set layout for window /tab page

### ISSUE THREAD

**Issue by Ajaymamtora** [folke/edgy.nvim#109]
### Did you check the docs?

- [X] I have read all the edgy.nvim docs

### Is your feature request related to a problem? Please describe.

It would be handy to activate edgy for the current tabpage with a different layout to the one passed to setup.

E.g. open a git tab page where Diffview is opened and and git log is open in another pinned view.

### Describe the solution you'd like

Be able to set the layout for vim.api.nvim_get_current_tabpage().

 This way you can have an independent layout from the default.

it could be a new method that you pass left,right etc the same was as the setup function

### Describe alternatives you've considered

I don’t think there’s another way to pin tabs in a different layout to the main one.

### Additional context

Could easily be useful in other contexts.

**Comment by rocket-engineer** [comment]
@Ajaymamtora Do you know [edgy-group.nvim](https://github.com/lucobellic/edgy-group.nvim)?

**Comment by rocket-engineer** [comment]
Yeah, I'm also not completely satisfied with the result, but maybe you can ask the maintainer for improvements. I have for example the same problem with loading specific groups. Currently, I'm using EdgyGroupSelect, but I also prefer a keymap for this task (and switching multiple groups at once). Switching to tabby.nvim is on my ToDo list.

**Comment by lucobellic** [comment]
@rocket-engineer, @Ajaymamtora, do not hesitate to open issues or ask questions in [Q&A discussions](https://github.com/lucobellic/edgy-group.nvim/discussions/new?category=q-a).
Based on your comments, I added basic usage documentation with tabby.nvim and `open_groups_by_key` function to open one or multiple groups by key.

**Comment by rocket-engineer** [comment]
@lucobellic Thx for the hint and the documentation! The problem on my side is the lack of time ;) But I'll come back to your offer soon!
