### ISSUE TITLE
bug: flickering when using symbols outline

### ISSUE THREAD

**Issue by Rukenshia** [folke/edgy.nvim#14]
### Did you check docs and existing issues?

- [X] I have read all the edgy.nvim docs
- [X] I have searched the existing issues of edgy.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-476+ga217675a6-Homebrew

### Operating system/version

MacOS 13.4

### Describe the bug

When I use the config example and navigate between different panes, my cursor suddenly gets stuck and things start to flicker. If I remove SymbolsOutline, things seem to go back to normal.

### Steps To Reproduce

1. Use the [Example setup](https://github.com/folke/edgy.nvim#-example-setup)
2. Open a repository (in my case it was my personal repo Rukenshia/saml2aws-auto)
3. See things go wild

### Expected Behavior

I can use the left sidebar correctly

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify('./.repro', ':p')

-- set stdpaths to use .repro
for _, name in ipairs({'config', 'data', 'state', 'cache'}) do
    vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        'git', 'clone', '--filter=blob:none',
        'https://github.com/folke/lazy.nvim.git', lazypath
    })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
    {
        'nvim-neo-tree/neo-tree.nvim', branch = 'v2.x', dependencies = {
            'nvim-lua/plenary.nvim', 'nvim-tree/nvim-web-devicons', -- not strictly required, but recommended
            'MunifTanjim/nui.nvim'
        }, config = true
    }, {'simrat39/symbols-outline.nvim', config = true},
    'folke/tokyonight.nvim', {
        {
            'folke/edgy.nvim', event = 'VeryLazy', opts = {
                bottom = {
                    {ft = 'qf', title = 'QuickFix'}, {
                        ft = 'help', size = {height = 20},
                        -- only show help buffers
                        filter = function(buf)
                            return vim.bo[buf].buftype == 'help'
                        end
                    }, {ft = 'spectre_panel', size = {height = 0.4}}
                }, left = {
                    -- Neo-tree filesystem always takes half the screen height
                    {
                        title = 'Neo-Tree', ft = 'neo-tree',
                        filter = function(buf)
                            return vim.b[buf].neo_tree_source == 'filesystem'
                        end, size = {height = 0.5}
                    }, {
                        title = 'Neo-Tree Git', ft = 'neo-tree',
                        filter = function(buf)
                            return vim.b[buf].neo_tree_source == 'git_status'
                        end, pinned = true,
                        open = 'Neotree position=right git_status'
                    }, {
                        title = 'Neo-Tree Buffers', ft = 'neo-tree',
                        filter = function(buf)
                            return vim.b[buf].neo_tree_source == 'buffers'
                        end, pinned = true,
                        open = 'Neotree position=top buffers'
                    }, {ft = 'Outline', pinned = true, open = 'SymbolsOutline'},
                    -- any other neo-tree windows
                    'neo-tree'
                }
            }
        }
    }
}
require('lazy').setup(plugins, {root = root .. '/plugins'})

vim.cmd.colorscheme('tokyonight')
-- add anything else here
```

**Comment by Rukenshia** [comment]
A short recording of what it looks like for me:

https://github.com/folke/edgy.nvim/assets/1899599/ebcb9d52-acdd-4e83-8cee-906a0a6a58e2

**Comment by folke** [comment]
Can you try with the latest version that I pushed half an hour ago?

**Comment by folke** [comment]
Are you using a nightly from after June 5th or neovim stable?

**Comment by Rukenshia** [comment]
> Are you using a nightly from after June 5th or neovim stable?

Yes, I'm on https://github.com/neovim/neovim/commit/a217675a67233ca2032cd668e919858d2aed92e7 at the moment (installed via homebrew). I also tried the stable release before (0.9.1) with the same result.

**Comment by folke** [comment]
I was able to reproduce it. HAs to do with settings of splitbelow and splitright. I'll push a fix in a bit

**Comment by folke** [comment]
Can you check if that indeed fixed it?

**Comment by Rukenshia** [comment]
@folke that fixed it indeed! Thanks a lot for the quick resolution, really appreciate your work ❤️

**Comment by madjxatw** [comment]
Neo-tree window is laggy and sometimes flickering when press `e` to expand its width to have truncated text in view. Is this caused by flickering limitation stated in the doc?

**Comment by folke** [comment]
Yes indeed. Currently you can't manually change window sizes
