### ISSUE TITLE
bug: while loading, the focus is sent back to the main buffer

### ISSUE THREAD

**Issue by adelin-b** [folke/edgy.nvim#29]
### Did you check docs and existing issues?

- [X] I have read all the edgy.nvim docs
- [X] I have searched the existing issues of edgy.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev

### Operating system/version

archlinux

### Describe the bug

When navigating between window on the left panel, the main buffer get the focus again

https://github.com/folke/edgy.nvim/assets/23508913/ba9b6eb1-2a90-470b-a149-a6e65a07a079

(I would be very interested on the debug method to use there as I have many other bug in my config and I don't think i have an efficient way of debuging thoses)

### Steps To Reproduce

- Run with docker
```
docker run -w /root -it --rm alpine:edge sh -uelic '
  apk add git lazygit neovim ripgrep alpine-sdk --update
  git clone https://github.com/adelin-b/LazyVim ~/.config/nvim
  cd ~/.config/nvim
  nvim
'
```
- Then press ```<leader>fo``` (filetree open)

- `c-j` / `c-k`  multiple time to move in the left panel, you can use `<` `>` for toggling the neotree panels and it will bug on thoses when you `c-j` and `c-k` mutiple times in a direction or another.

It will go back to the main buffer 

### Expected Behavior

It should stay on the left panel

### Repro

```Lua
^ docker command above, if it doesn't work i can try another repro here.
```

**Comment by folke** [comment]
That is on purpose. Reason is that when one of those sidebar plugins load, they typically will present information from the current buffer.

But since the current buffer would have been an empty edgy window, nothing would be shown. Worst case, the plugin would show errors.

So that's why edgy always goes to the main editor when loading a pinned view.

**Comment by adelin-b** [comment]
Oh nice, do you think it could be possible to load and hide the panel, so it act as it was alway open rather than lazy loaded when selected ? 
a `lazy=false` in the edgy config maybe.

**Comment by folke** [comment]
You can use `require("edgy").toggle()`.
This will open (or close) all edgy sidebars and load all

**Comment by adelin-b** [comment]
ok, what i see here is that it open the sidebar but some views are still hidden until we open it.

Here i was trying to reach the buffer panel but it blocked until i arrived by the bottom . I didnt pressed `C-L` once in this video. and I toggle using 
`: lua require('edgy'.toggle()`

https://github.com/folke/edgy.nvim/assets/23508913/49a6f1c8-fea3-48e2-8415-321b1fea8a10


Its a piece of full spec config i took on LazyVim doc, with just overseer added. 

https://github.com/adelin-b/LazyVim/blob/main/lua/plugins/ui.lua#L232C1-L362

So the loading happen and is triggered again when we go on the tab and not when opening the all at once.

**Comment by folke** [comment]
you closed the buffer list instead of hiding it with `<c-q>`, so yes, it would load it again in the way I mentioned before
