### ISSUE TITLE
feature: Window title

### ISSUE THREAD

**Issue by serhez** [folke/edgy.nvim#36]
### Did you check the docs?

- [X] I have read all the edgy.nvim docs

### Is your feature request related to a problem? Please describe.

I use edgy as a left-side pane to have different cwd-dependent views, e.g., a file tree, a tree of modified files as tracked by git and a tree of open buffers. I use `neo-tree` sources to display these. However, I find the `hide_root_node` option of `neo-tree` quite handy, as I see the redundant root node always displaying the cwd for all views. By hiding the root node, I don't waste horizontal nor vertical space on this information, but it would be good to have it at the top of the whole `edgy` sidebar.

Not hiding the root nodes:
![Screenshot 2023-07-19 at 23 01 56](https://github.com/folke/edgy.nvim/assets/18057093/1322d3bf-0e95-4cfe-98c9-5a51b0b4298a)

Hiding the root nodes:
![Screenshot 2023-07-19 at 23 01 31](https://github.com/folke/edgy.nvim/assets/18057093/af331f7f-8717-4a90-a4af-e2ab5f006e67)

### Describe the solution you'd like

It'd be great to add a `title` option to the windows, i.e., to `left`, `right`, `top` and `bottom`.

### Describe alternatives you've considered

Using the `bufferline` title to display this information.

**Comment by folke** [comment]
That's out of scope for this plugin. Not interested in adding this functionality
