### ISSUE TITLE
bug: flickering with neo-tree auto expand enabled

### ISSUE THREAD

**Issue by pkazmier** [folke/edgy.nvim#37]
### Did you check docs and existing issues?

- [X] I have read all the edgy.nvim docs
- [X] I have searched the existing issues of edgy.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.1

### Operating system/version

MacOS Ventura 13.4

### Describe the bug

When neo-tree auto expand is enabled (`e` keybinding), If Neo-tree needs to expand due to width of its contents , the screen flickers as the width of the neo-tree sidebar quickly alternates between widths. Here is a video of it occurring.

https://github.com/folke/edgy.nvim/assets/747855/ea0894ee-db11-4f0b-9f73-0c3a7bcfc2dd

### Steps To Reproduce

1. From command line, open a file in a deeply nested directory. This will force Neo-tree to auto expand in the next step.
2. Open neo-tree, enable auto expand (`e`).
3. Move between windows and flickering will begin.
4. Disable auto expand (`e`) and flickering will stop.

### Expected Behavior

No flickering.

### Repro

```Lua
My lua skills aren't the good. I've tried for the past 30 minutes to come up with a bare minimum config, but I keep hitting a wall. I'm a new user to LazyVim and I'm using the starter kit with edgy extra enabled.
```

**Comment by folke** [comment]
Yes, this won't work properly with edgy. Can't fix

**Comment by pkazmier** [comment]
Understood. Thanks.

**Comment by axkirillov** [comment]
@pkazmier Hi
I was able to make it work. It's not a perfect solution though, in some cases you will still get flicker.
https://github.com/folke/edgy.nvim/discussions/126
