### ISSUE TITLE
bug: missing border character upon open

### ISSUE THREAD

**Issue by pkazmier** [folke/edgy.nvim#38]
### Did you check docs and existing issues?

- [X] I have read all the edgy.nvim docs
- [X] I have searched the existing issues of edgy.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.1 and NVIM v0.10.0-dev-695+g58f948614

### Operating system/version

MacOS Ventura 13.4

### Describe the bug

The last vertical bar for the border is not initially drawn. Most often, I see an empty space character where the border should be, but it simply depends on the width/height of the terminal and contents of the main buffer. Here are a few examples:

Icon from starter shown when term size is 25x111:
<img width="889" alt="image" src="https://github.com/folke/edgy.nvim/assets/747855/2549fc65-121a-4075-9104-8edba36375bc">

Space char shown when term size is 25x119 chars:
<img width="945" alt="image" src="https://github.com/folke/edgy.nvim/assets/747855/479ceb87-92f2-4d20-ad5d-298acecc01f1">

But as soon as you resize the window or open one of the sections, the character is drawn correctly. For example, in the below image, I simply made the terminal wider and then shorter again to the original size:
<img width="889" alt="image" src="https://github.com/folke/edgy.nvim/assets/747855/697549de-9e26-4361-a8bb-65460f6c6272">

Note: This is easy to overlook with the standard border color of Tokyonight when a space character takes the place of the border.  But I prefer a slightly brighter border to help distinguish my windows in vim, so I set my Tokyonight border color to the same color as comments. And that's when it stood out like a sore thumb.

### Steps To Reproduce

1. Open a terminal and set its size to 25x111 characters (`stty size`).
2. Open neovim with the standard starter screen from LazyVim.
3. Open neo-tree using `<leader>e`.
4. You should see the icon I see in the screen shot.

To fix, simply resize the terminal window or open the neo-tree Buffers section.

I have tested with the latest nightly version from nvim as one of the prior issues stated that an upstream fix was posted, so I was unsure if that might be related, so I tested both 0.9.1 as well as nightly neovim. Problem happens on both.

### Expected Behavior

I expect it to draw the full border as in the screenshot above.

### Repro

```Lua
I am struggling to create a simple config (my Lua Nvim skills aren't so great).
I was able to reproduce with a LazyVim starter kit with only the edgy extra enabled.
```

**Comment by folke** [comment]
I noticed that as well. Those characters are not drawn by edgy. That's a Neovim bug

**Comment by pkazmier** [comment]
I'm 0 for 2 today 😄
