### ISSUE TITLE
feature: dynamic title

### ISSUE THREAD

**Issue by Chaitanyabsprip** [folke/edgy.nvim#43]
### Did you check the docs?

- [X] I have read all the edgy.nvim docs

### Is your feature request related to a problem? Please describe.

I wish to have dynamic title for my quick fix windows, e.g., I open diagnostics in qf then my title should be Diagnostics, I open buffers in qf, then my title should be buffers, etc.

### Describe the solution you'd like

title field could be a function that returns a string, this way every time a new window is opened, title string could be obtained from this function.

### Describe alternatives you've considered

none -

**Comment by willothy** [comment]
You can use regular winbar syntax to call a function in the title, such as `%{%v:lua.custom_title()%}`. Once #46 is merged, the width will be calculated properly for format strings. Hope  that helps
