### ISSUE TITLE
bug: Dropbar and Edgy not working together properly

### ISSUE THREAD

**Issue by franroa** [folke/edgy.nvim#44]
### Did you check docs and existing issues?

- [X] I have read all the edgy.nvim docs
- [X] I have searched the existing issues of edgy.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10-dev

### Operating system/version

Manjaro 6.1.44

### Describe the bug

Using LazyVim, with edgy default's config and dropbar default's config an error is thrown.

I have also created an issue in dropbar project, because I am not sure where could be the root's cause:
https://github.com/Bekaboo/dropbar.nvim/issues/72

### Steps To Reproduce

1. Install LazyVim
2. add dropbar plugin
3. Open a file
4. Open neo-tree (with edgy layout)

### Expected Behavior

No error is thrown

### Repro

```Lua
No idea how to reproduce with minimal config. The issue appears on a fresh LazyVim config with edgy active and dropbar plugin installed
```

**Comment by thehappyboy** [comment]
{
		"Bekaboo/dropbar.nvim",
		event = "VeryLazy",
		config = function()
			require("dropbar").setup({
				general = {
					enable = function(buf, win)
						return not vim.api.nvim_win_get_config(win).zindex
							and vim.bo[buf].buftype == ""
							and vim.bo[buf].buftype ~= "nofile"
							and vim.api.nvim_buf_get_name(buf) ~= ""
							and not vim.wo[win].diff
					end,
				},
			})
		end,
	},

**Comment by thehappyboy** [comment]
Now, I disabled update events "WinResized" to solve this issue.

{
		"Bekaboo/dropbar.nvim",
		event = "VeryLazy",
		config = function()
			require("dropbar").setup({
				general = {
					update_events = {
						win = {
							"CursorMoved",
							"CursorMovedI",
							"WinEnter",
							-- "WinResized",
						},
						buf = {
							"BufModifiedSet",
							"FileChangedShellPost",
							"TextChanged",
							"TextChangedI",
						},
						global = {
							"DirChanged",
							"VimResized",
						},
					},
				},
			})
		end,
	}

**Comment by folke** [comment]
Seems like there's a work-around. closing...

**Comment by franroa** [comment]
thanks for the workaround @thehappyboy
