### ISSUE TITLE
bug: Help window not displayed in edgy after following tags

### ISSUE THREAD

**Issue by tummetott** [folke/edgy.nvim#61]
### Did you check docs and existing issues?

- [X] I have read all the edgy.nvim docs
- [X] I have searched the existing issues of edgy.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.4 Build type: Release LuaJIT 2.1.1696795921

### Operating system/version

MacOs 13.4.1

### Describe the bug

I've set up the help window to be displayed in `edgy.nvim`. When navigating between help files using `<C-]>` to follow tags, the new help files no longer appear to be an edgy window. This is noticeable through changes in the winbar, and the default keymap `q` to close the window ceases to work.

### Steps To Reproduce

1. `nvim --clean -u repro.lua`
2. `:help :cnext`
3. `/switchbuf<cr>`
4. `<C-]>`

--> new helpfile is no edgy window

### Expected Behavior

the jumped helpfile is still an edgy window

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
    "folke/tokyonight.nvim",
    {
        "folke/edgy.nvim",
        opts = {
            bottom = {
                { ft = 'help' },
            }
        }
    },
}
require("lazy").setup(plugins, {
    root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
```

**Comment by tummetott** [comment]
I discovered that the bug can also be replicated by opening two help windows sequentially:

`:h help`
`:h treesitter`

**Comment by folke** [comment]
should be fixed
