### ISSUE TITLE
bug: When I use telescope's goto symbol under zen-mode, zen-mode quit

### ISSUE THREAD

**Issue by horaoen** [folke/edgy.nvim#64]
### Did you check docs and existing issues?

- [X] I have read all the edgy.nvim docs
- [X] I have searched the existing issues of edgy.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

macos 14.2.1

### Describe the bug

Describe as the title and I'am using lazyvim. I'm guessing this is an edgy problem because when I commented lazyvim's edgy plugin import everything worked fine.
<img width="1920" alt="图片" src="https://github.com/folke/zen-mode.nvim/assets/92006580/4b5e097b-3e79-4e08-9b52-a8435a872651">
<img width="1920" alt="图片" src="https://github.com/folke/zen-mode.nvim/assets/92006580/56185991-b95e-4085-9b1a-3ac15064e754">

### Steps To Reproduce

1. open a file and start zen-mode.
2. type <leader>ss to(lazyvim) call telescope's goto symbol.
3. choose a symbol.
4. then zen mode quited.

### Expected Behavior

1. zen-mode not quit.

**Comment by folke** [comment]
this has nothing to do with edgy.
