### ISSUE TITLE
bug: QuickFix is stuck

### ISSUE THREAD

**Issue by yaotutu** [folke/edgy.nvim#67]
### Did you check docs and existing issues?

- [X] I have read all the edgy.nvim docs
- [X] I have searched the existing issues of edgy.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2284+gf6042d5c3 && NVIM 9.5

### Operating system/version

Macos 14.11

### Describe the bug

If I open a help window first and then open a quickfix window, it freezes. However, if I adjust the configuration file and place the quickfix window at the top, it opens normally.
If there are other window configurations before the quickfix window, and you open them before opening the quickfix window, you may encounter such issues.

### Steps To Reproduce

1. :help
2. :copen

### Expected Behavior

Open the quickfix window normally

### Repro

```Lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable", -- latest stable release
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
    {
        "folke/edgy.nvim",
        event = "VeryLazy",
        init = function()
            vim.opt.laststatus = 3
            vim.opt.splitkeep = "screen"
        end,
        opts = {
            bottom = {
                {
                    ft = "help",
                    size = { height = 20 },
                    -- only show help buffers
                    filter = function(buf)
                        return vim.bo[buf].buftype == "help"
                    end,
                },
                { ft = "qf", title = "QuickFix" },
            },
        },
    }
})
```

**Comment by tummetott** [comment]
Yes i can second this. also had exactly this freeze several times.
