### ISSUE TITLE
bug: ui is broken 

### ISSUE THREAD

**Issue by nugmubs** [folke/edgy.nvim#80]
### Did you check docs and existing issues?

- [X] I have read all the edgy.nvim docs
- [X] I have searched the existing issues of edgy.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

MacOS lastest 

### Describe the bug

when I select a terminal buffer on left side panel, edgy.nvim ui is broken. 

![image](https://github.com/folke/edgy.nvim/assets/61725446/aa0a9172-279e-4a26-9390-70c2734810d3)

![image](https://github.com/folke/edgy.nvim/assets/61725446/5fa88a19-aaf5-4e2b-8371-0e2f390470d1)

### Steps To Reproduce

1. just click terminal buffer... 

### Expected Behavior

it should be placed under text editor

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/edgy.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by izelnakri** [comment]
@folke This does happen on NeoVim v0.10, fyi. 


I also wonder why this is happening... I'm currently checking to see if I really need this plugin API/configuration wise natively by using nvim lua api, or whether it will cause more trouble then benefit having this plugin.

**Comment by Vssblt** [comment]
That issue also occurred on my neovim, but upgrading to the latest version of edgy.nvim and Neovim fixed it.
At least, it is working fine today.

**Comment by Vssblt** [comment]
And if you are using older version, you can also fix this issue by disabling animations.
