### ISSUE TITLE
feature: Disable animation for a window?

### ISSUE THREAD

**Issue by Ajaymamtora** [folke/edgy.nvim#81]
### Did you check the docs?

- [X] I have read all the edgy.nvim docs

### Is your feature request related to a problem? Please describe.

Nvim-spectre doesn't work well when an animation is enabled and it's pinned to the bottom.

### Describe the solution you'd like

It would be good to disable the edgy animation for specific items

```lua
      {
        ft = "spectre_panel",
        title = "Spectre",
        animation = false,
        size = {
          height = 0.4,
        },
      },
```

### Describe alternatives you've considered

Disabling all animations, but I don't want to disable it for all windows

**Comment by folke** [comment]
that has been fixed
