### ISSUE TITLE
bug: incoherent behaviour when filetype is empty

### ISSUE THREAD

**Issue by LoricAndre** [folke/edgy.nvim#84]
### Did you check docs and existing issues?

- [X] I have read all the edgy.nvim docs
- [X] I have searched the existing issues of edgy.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-dev-164+g3a1515bfe

### Operating system/version

Linux loric 6.9.3-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Fri, 31 May 2024 15:14:26 +0000 x86_64 GNU/Linux

### Describe the bug

When edgy is configured with a filter but an empty filetype, the window title gets set but the window itself is not controlled by edgy.
I noticed this running Overseer.nvim.

![image](https://github.com/folke/edgy.nvim/assets/57358788/31f11e2d-a452-4c25-b90a-7d6e87371d03)

As you can see in the screenshot, the 'Overseer runner' window does not follow edgy config (contrary to the other 2), and is not toggled with edgy.

### Steps To Reproduce

1. Install overseer.nvim
2. Add `{ ft = "", filter = function(buf, win) return vim.b.overseer_task ~= nil end, title = "Overseer Runner" }` to the edgy bottom section
3. Run `:OverseerToggle`

### Expected Behavior

The window title should be set and the window should be managed by edgy.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/edgy.nvim",
  'stevearc/overseer.nvim',
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
require('overseer').setup()
require('edgy').setup({    bottom = {
      {
        ft = "toggleterm",
        open = "ToggleTerm",
        size = {
          height = 0.3,
        },
        filter = function(_, win)
          return vim.api.nvim_win_get_config(win).relative == ""
        end,
        pinned = true,
      },
      "Trouble",
      { ft = "qf", title = "QuickFix" },
      { ft = "OverseerList", title = "Overseer List" },
      { title = "Overseer Runner", ft = "", filter = function (buf, win)
        return vim.b.overseer_task ~= nil
      end,
        size = {
          height = 0.3,
        },
      }
    },
})
```

**Comment by folke** [comment]
yes, edgy needs a filetype to work
